title: Paul Brodzinski
description: Documenting the journey to my next contract.
url: "https://paulbrodzinski.com"
author: Paul Brodzinski

theme: minima

minima:
  skin: dark

show_excerpts: true

plugins:
  - jekyll-feed
